package SIG.view;

import SIG.controller.C_SIG;
import SIG.controller.C_SIGselection;
import SIG.model.HeaderTableModel;
import SIG.model.InvoiceHeader;
import SIG.model.InvoiceLine;
import SIG.model.LineTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author menna
 */
public class SIGFramee extends javax.swing.JFrame {

    /**
     * Creates new form SIGFramee
     */
    public SIGFramee() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesTable = new javax.swing.JTable();
        invoicesTable.getSelectionModel().addListSelectionListener(Selection);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        invoicedateLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        invoicetotalLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceLineTable = new javax.swing.JTable();
        newinvoicebtn = new javax.swing.JButton();
        newinvoicebtn.addActionListener(Listener);
        deleteinvoicebtn = new javax.swing.JButton();
        deleteinvoicebtn.addActionListener(Listener);
        newlinebtn = new javax.swing.JButton();
        newlinebtn.addActionListener(Listener);
        deletelinebtn = new javax.swing.JButton();
        deletelinebtn.addActionListener(Listener);
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        Load = new javax.swing.JMenuItem();
        Load.addActionListener(Listener);
        Save = new javax.swing.JMenuItem();
        Save.addActionListener(Listener);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(invoicesTable);

        jLabel1.setText("Invoice Name");

        jLabel2.setText("Customer Name");

        jLabel3.setText("Invoice Date");

        jLabel4.setText("Invoice Total");

        numLabel.setText("...");

        invoicedateLabel.setText("...");

        nameLabel.setText("...");

        invoicetotalLabel.setText("...");

        invoiceLineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(invoiceLineTable);

        newinvoicebtn.setText("New Invoice");

        deleteinvoicebtn.setText("Delete Invoice");

        newlinebtn.setText("New Line");

        deletelinebtn.setText("Delete Line");

        FileMenu.setText("File");

        Load.setText("Load File");
        FileMenu.add(Load);

        Save.setText("Save File");
        FileMenu.add(Save);

        jMenuBar1.add(FileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(invoicetotalLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(numLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(invoicedateLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(newinvoicebtn)
                .addGap(69, 69, 69)
                .addComponent(deleteinvoicebtn)
                .addGap(88, 88, 88)
                .addComponent(newlinebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(deletelinebtn)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(numLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(invoicedateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(invoicetotalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newinvoicebtn)
                        .addComponent(deleteinvoicebtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newlinebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deletelinebtn)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               SIGFramee f = new SIGFramee();
     
              f.setVisible(true);
              f.setTitle("Sales Invoice Generator");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem Load;
    private javax.swing.JMenuItem Save;
    private javax.swing.JButton deleteinvoicebtn;
    private javax.swing.JButton deletelinebtn;
    private javax.swing.JTable invoiceLineTable;
    private javax.swing.JLabel invoicedateLabel;
    private javax.swing.JTable invoicesTable;
    private javax.swing.JLabel invoicetotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton newinvoicebtn;
    private javax.swing.JButton newlinebtn;
    private javax.swing.JLabel numLabel;
    // End of variables declaration//GEN-END:variables
    private C_SIG Listener =new C_SIG(this);
    private C_SIGselection Selection = new C_SIGselection(this);
    public static DateFormat df= new SimpleDateFormat("dd-MM-yyyy");
    private ArrayList<InvoiceHeader> invoiceHeaderArrayList;
    private ArrayList<InvoiceLine> lineArrayList;
    private LineTableModel lineTable = new LineTableModel();
    private HeaderTableModel headerTable = new HeaderTableModel();
    private InvoiceLineDialog newLine = new InvoiceLineDialog();
    private InvoiceHeaderDialog newInvoice = new InvoiceHeaderDialog();
    
    public C_SIG getcontroller(){
        return Listener;
    }
    
    public void setcontroller(C_SIG Listener){
       this.Listener = Listener;
    }

    public ArrayList<InvoiceHeader> getInvoiceHeaderArrayList() {
        return invoiceHeaderArrayList;
        
    }

    public ArrayList<InvoiceLine> getLineArrayList(){
  
       return lineArrayList;
    }
    public void setInvoiceHeaderArrayList(ArrayList<InvoiceHeader> invoiceHeaderArrayList){
         this.invoiceHeaderArrayList = invoiceHeaderArrayList;
    }
    
    public void setLineArrayList(ArrayList<InvoiceLine> lineArrayList ){
        this.lineArrayList = lineArrayList;
    }
    
    public InvoiceHeader getNO(int num){
        for(InvoiceHeader Header: invoiceHeaderArrayList){
            if(Header.getNum() == num){
              return Header;
            }
        }return null;
    }
    
    public JTable getInvoicesTable(){
        return invoicesTable;
    }
    
    public JTable getInvoiceLineTable(){
       return invoiceLineTable;
    }
    
    public void setInvoicesTable (JTable invoicesTable){
        this.invoicesTable = invoicesTable;
        
    }
    
    public void setInvoiceLineTable(JTable invoiceLineTable){
        this.invoiceLineTable = invoiceLineTable;
    
    }
    
    public void setHeaderTableModel(HeaderTableModel headerTable){
        this.headerTable = headerTable;
    }
    
    public HeaderTableModel getHeaderTableModel(){
        return headerTable;
    }
    
    public void setLineTableModel(LineTableModel lineTable){
        this.lineTable = lineTable;
    }
     
    public LineTableModel getLineTableModel(){
        return lineTable;
    }
    
    public JLabel getNoLabel(){
        return numLabel;
    }
    
    public void setNOLabel(JLabel numLabel){
        this.numLabel = numLabel;
    }
    
    public JLabel getCustomerNameLabel(){
    
        return nameLabel;
    }
    
    public void setCustomerNameLabel(JLabel nameLabel){
        this.nameLabel = nameLabel;
    }
   
    public JLabel getDateLabel(){
        return invoicedateLabel;
    }
    
   public void setDatelabel(JLabel invoicedateLabel){
       this.invoicedateLabel = invoicedateLabel;
   }
   
   public JLabel getTotalLabel(){
       return invoicetotalLabel;
   }
    
   public void setTotalLabel(JLabel invoicetotalLabel){
       this.invoicetotalLabel = invoicetotalLabel;
   }
    
   public InvoiceHeaderDialog getNewInvoice(){
       return newInvoice;
   }
   public void setNewInvoice(InvoiceHeaderDialog newInvoice){
       this.newInvoice =newInvoice;
   }
   
   public InvoiceLineDialog getNewLine(){
       return newLine;
   
   }
   public void setNewLine (InvoiceLineDialog newLine){
       this.newLine = newLine;
   }
    
}
